"""add so_pi tables

Revision ID: 6d2027b60e88
Revises: 4418c365b2ee
Create Date: 2026-08-10 17:09:23.222108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2027b60e88'
down_revision = '4418c365b2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proficiency_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('so_pis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_program', sa.String(length=120), nullable=False),
    sa.Column('so_code', sa.String(length=30), nullable=False),
    sa.Column('so_description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_program', 'so_code', name='uq_so_pis_program_code')
    )
    op.create_table('performance_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_id', sa.Integer(), nullable=False),
    sa.Column('pi_code', sa.String(length=30), nullable=False),
    sa.Column('pi_description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['so_id'], ['so_pis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('so_id', 'pi_code', name='uq_pis_so_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_indicators')
    op.drop_table('so_pis')
    op.drop_table('proficiency_levels')
    # ### end Alembic commands ###
