"""single study_program per user

Revision ID: 898d52d28748
Revises: 9092647ecee5
Create Date: 2026-08-10 17:53:35.602236

"""
import json

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '898d52d28748'
down_revision = '9092647ecee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_program', sa.String(length=120), nullable=True))

    # Backfill study_program from the old JSON list (use its first entry).
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, study_programs FROM users")).fetchall()
    for row in rows:
        program = None
        if row[1]:
            try:
                value = json.loads(row[1])
                if isinstance(value, list) and value:
                    program = str(value[0])
            except (TypeError, ValueError):
                program = None
        conn.execute(
            sa.text("UPDATE users SET study_program = :sp WHERE id = :id"),
            {"sp": program, "id": row[0]},
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('study_programs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_programs', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.drop_column('study_program')
    # ### end Alembic commands ###
