"""add user study_programs

Revision ID: 9092647ecee5
Revises: 6d2027b60e88
Create Date: 2026-08-10 17:29:23.535098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9092647ecee5'
down_revision = '6d2027b60e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_programs', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('study_programs')

    # ### end Alembic commands ###
