"""drop pi level

Revision ID: ce92a3c912da
Revises: 898d52d28748
Create Date: 2026-08-10 18:18:21.240630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce92a3c912da'
down_revision = '898d52d28748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_indicators', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
