"""add course shared_with

Revision ID: d675cc5c1d87
Revises: ce92a3c912da
Create Date: 2026-08-10 19:06:25.894132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd675cc5c1d87'
down_revision = 'ce92a3c912da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('shared_with')

    # ### end Alembic commands ###
